---
# tasks file for shell_users
- name: Ensure user do exists
  user:
    name: "{{ item.name }}"
    createhome: yes
    home: "{{ item.home|default(omit) }}"
    shell: "/bin/bash"
    groups: "{{ item.groups|default('') }}"
    state: "{{ item.state|default('present') }}"
  with_items: "{{ shell_users }}"

- name: Ensure ssh key is loaded
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', inventory_dir + '/public_keys/' + item.name + '.pub') }}"
    state: "{{ item.state|default('present') }}"
  with_items: "{{ shell_users }}"
  when: 
    - not shell_users_ignore_keys

- name: Ensure sudo on root is available
  copy:
    content: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL\n"
    dest: "/etc/sudoers.d/{{ item.name }}"
    validate: /usr/sbin/visudo -cf %s
  with_items: "{{ shell_users }}"
  when:
    - item.state == "present"

- name: Ensure sudo on root is not available
  file:
    path: "/etc/sudoers.d/{{ item.name }}"
    state: absent
  with_items: "{{ shell_users }}"
  when:
    - item.state == "absent"

